services:
  frontend:
    image: aa
    container_name: openshock-frontend
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - PUBLIC_SITE_URL=http://localhost:3000
      - PUBLIC_SITE_SHORT_URL=http://lh:3000
      - PUBLIC_BACKEND_API_URL=https://test
      - PUBLIC_GATEWAY_CSP_WILDCARD=http://*.localhost:3000
      - PUBLIC_SITE_NAME=OpenShock
      - PUBLIC_SITE_DESCRIPTION=a free and open-source ecosystem to control various shock collars over the internet.
      - PUBLIC_GITHUB_PROJECT_URL=https://github.com/OpenShock
      - PUBLIC_DISCORD_INVITE_URL=https://discord.gg/OpenShock
      - PUBLIC_TURNSTILE_DEV_BYPASS_VALUE=dev-bypass
      - PUBLIC_DEVELOPMENT_BANNER=false
